/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

/**
 *
 * @author hp
 */

import static hostel.AlterFamilyDetails.name;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class AlterHostelDetails extends javax.swing.JFrame {

    static String name = AlterPerson.Name;
    ResultSet resultSet;
    Statement stmnt;
    String selectedRoom;
    String Roomno;
    String oldroom;
    String RoomNo;
    String oldPerson;
    String person;
    String available;
    NoSpace f4;
    InvalidData Error = new InvalidData();
    /**
     * Creates new form AlterHostelDetails
     */
    public AlterHostelDetails() {
        initComponents();
        
        CurrentHeading1.setText(name);
        try
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
            }
            
            catch(ClassNotFoundException a)
            {
                System.out.println("Error class not Found");
            }
            
            String userID = "root";
            String password = "iamshlok";
            String URL = "jdbc:mysql://localhost:3306/hostel";
            
            Connection connect = DriverManager.getConnection(URL, userID, password);
            stmnt = connect.createStatement();
            
            System.out.println("Connection Established!");
            
            String query = "SELECT * FROM HostelDetails Where(personName = '" + name + "');";
            
            resultSet = stmnt.executeQuery(query);
            resultSet.next();
            
            FeesField.setText(resultSet.getString(4));
            CautionField.setText(resultSet.getString(3));
            RoomComboBox.setSelectedItem(resultSet.getString(2));
            oldroom = resultSet.getString(2);
            oldPerson = resultSet.getString(5);
        }
        
        catch(SQLException a)
        {
            System.out.println("Error");
            System.out.println(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CurrentHeading1 = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        FeesField = new javax.swing.JTextField();
        CautionField = new javax.swing.JTextField();
        CautionHeading = new javax.swing.JLabel();
        RoomComboBox = new javax.swing.JComboBox<>();
        RoomNumberHeading = new javax.swing.JLabel();
        RoomNumberHeading1 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CurrentHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentHeading1.setText("Empty");

        Heading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Hostel Details");

        jSeparator2.setAutoscrolls(true);
        jSeparator2.setFocusable(true);

        FeesField.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        FeesField.setText("0");
        FeesField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FeesFieldFocusLost(evt);
            }
        });

        CautionField.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        CautionField.setText("0");
        CautionField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CautionFieldFocusLost(evt);
            }
        });
        CautionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautionFieldActionPerformed(evt);
            }
        });

        CautionHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        CautionHeading.setText("Caution Money");

        RoomComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        RoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Empty>", "Ground - 1", "Ground - 2", "Ground - 3", "First - 1", "First - 2", "First - 3" }));
        RoomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomComboBoxActionPerformed(evt);
            }
        });

        RoomNumberHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        RoomNumberHeading.setText("Room Number");

        RoomNumberHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        RoomNumberHeading1.setText("Fees");

        SaveButton.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        SaveButton.setText("Save & Exit");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CautionHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RoomNumberHeading1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RoomNumberHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CautionField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FeesField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(RoomComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentHeading1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomNumberHeading)
                    .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomNumberHeading1)
                    .addComponent(FeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CautionHeading)
                    .addComponent(CautionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CautionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CautionFieldActionPerformed

    private void RoomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomComboBoxActionPerformed
        // TODO add your handling code here:

        selectedRoom = (String)RoomComboBox.getSelectedItem();

        if(selectedRoom.equals("<Empty>"))
        SaveButton.setEnabled(false);

        else
        {
            try
            {
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                }

                catch(ClassNotFoundException a)
                {
                    System.out.println("Error class not Found");
                }

                String userID = "root";
                String password = "iamshlok";
                String URL = "jdbc:mysql://localhost:3306/hostel";

                Connection connect = DriverManager.getConnection(URL, userID, password);
                Statement stmnt = connect.createStatement();

                System.out.println("Connection Established!");
                Roomno = "Empty";
                String query;

                query = "SELECT * FROM RoomInfo WHERE(Room = '" + selectedRoom + "');";
                resultSet = stmnt.executeQuery(query);

                resultSet.next();
                String Available = "NO";

                int noofp = resultSet.getInt(3);

                if(resultSet.getInt(4) == 0)
                {
                    person = "Person1";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }

                else if(resultSet.getInt(5) == 0 && Available.equals("NO"))
                {
                    person = "Person2";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }

                else if(resultSet.getInt(6) == 0 && Available.equals("NO") && resultSet.getString(1).equals("First - 3"))
                {
                    person = "Person3";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }

                else if(resultSet.getInt(7) == 0 && Available.equals("NO") && resultSet.getString(1).equals("First - 3"))
                {
                    person = "Person4";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }

                if(Available.equals("YES"))
                {
                    RoomNo = Roomno;
                    SaveButton.setEnabled(true);
                }

                else
                {
                    SaveButton.setEnabled(false);
                    RoomComboBox.setSelectedItem("<Empty>");
                    f4 = new NoSpace();

                    f4.setVisible(true);
                }
            }
            catch(SQLException a)
            {
                System.out.println("Error");
                System.out.println(a);
            }
        }
    }//GEN-LAST:event_RoomComboBoxActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    
        if(RoomComboBox.getSelectedItem().equals("<Empty>"))
        {
            Error = new InvalidData();
            Error.setVisible(true);
        }
        
        else
        {
            if(FeesField.getText().equals("") || (FeesField.getText().equals("0")))
            {
                Error = new InvalidData();
                Error.setVisible(true);
            }
            
            else
            {
                if(CautionField.getText().equals("") || (CautionField.getText().equals("0")))
                {
                    Error = new InvalidData();
                    Error.setVisible(true);
                }
                
                else
                {
                    try
                    {
                        String query = "DELETE FROM HostelDetails WHERE(personName = '" + name + "');";
                        stmnt.executeUpdate(query);

                        System.out.println("DELETE DONE!");

                        query = "INSERT INTO HostelDetails VALUES('" + name + "', '" + RoomNo + "', " + CautionField.getText() + ", " + FeesField.getText()
                        + ", '" + person + "');";

                        stmnt.executeUpdate(query);

                        query = "UPDATE RoomInfo SET " + oldPerson + " = 0 WHERE(Room = '" + oldroom + ");";
                        stmnt.executeUpdate(query);

                        query = "UPDATE RoomInfo SET " + EntryForm6.person + " = " + EntryForm2.ID + " WHERE(Room = '" + EntryForm6.Roomno + "');";

                        System.out.println("Save DONE!");

                    }

                    catch(SQLException b)
                    {
                        System.out.println("Error");
                        System.out.println(b);
                    }

                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void FeesFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FeesFieldFocusLost
        // TODO add your handling code here:
        
        try
        {
            long p = Long.parseLong(FeesField.getText());
        }
        
        catch(NumberFormatException a)
        {
            System.out.println("The Fees Format is wrong.");
            FeesField.setText("");
            Error = new InvalidData();
            Error.setVisible(true);
        }
    }//GEN-LAST:event_FeesFieldFocusLost

    private void CautionFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CautionFieldFocusLost
        // TODO add your handling code here:
               
        try
        {
            long p = Long.parseLong(CautionField.getText());
        }
        
        catch(NumberFormatException a)
        {
            System.out.println("The Fees Format is wrong.");
            CautionField.setText("");
            Error = new InvalidData();
            Error.setVisible(true);
        }
    }//GEN-LAST:event_CautionFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterHostelDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterHostelDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterHostelDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterHostelDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterHostelDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CautionField;
    private javax.swing.JLabel CautionHeading;
    private javax.swing.JLabel CurrentHeading1;
    private javax.swing.JTextField FeesField;
    private javax.swing.JLabel Heading;
    private javax.swing.JComboBox<String> RoomComboBox;
    private javax.swing.JLabel RoomNumberHeading;
    private javax.swing.JLabel RoomNumberHeading1;
    private javax.swing.JButton SaveButton;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
