/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

/**
 *
 * @author hp
 */
import static hostel.AlterFamilyDetails.name;
import static hostel.EntryForm5.Error;
import static hostel.EntryForm5.Worknumber;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class AlterCurrentDetails extends javax.swing.JFrame {

    static String name = AlterPerson.Name;
    Statement stmnt;
    ResultSet RS;
    String WorkingCondition = "No";
    /**
     * Creates new form AlterCurrentDetails
     */
    public AlterCurrentDetails() {
        initComponents();
        
        CurrentHeading1.setText(name);
        
        try
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
            }
            
            catch(ClassNotFoundException a)
            {
                System.out.println("Error class not Found");
            }
            
            String userID = "root";
            String password = "iamshlok";
            String URL = "jdbc:mysql://localhost:3306/hostel";
            
            Connection connect = DriverManager.getConnection(URL, userID, password);
            stmnt = connect.createStatement();
            
            System.out.println("Connection Established!");
            
            String query = "SELECT * FROM CDetails Where(personName = '" + name + "');";
            
            RS = stmnt.executeQuery(query);
            RS.next();
            
            InstitutionField.setText(RS.getString(2));
            GradeComboBox.setSelectedItem(RS.getString(3));
            
            if(RS.getString(4).equals("Yes"))
            {
                YesButton.setSelected(true);
                WorkingCondition = "Yes";
            }
            else if(RS.getString(4).equals("No"))
            {
                NoButton.setSelected(true);
                WorkingCondition = "No";
                WorkPlaceField.setEnabled(false);
                WorkNumberField.setEnabled(false);
                WorkAddressArea.setEnabled(false);
            }    
                
            WorkPlaceField.setText(RS.getString(6));
            WorkNumberField.setText(RS.getString(7));
            WorkAddressArea.setText(RS.getString(6));
        }
        
        catch(SQLException a)
        {
            System.out.println("Error");
            System.out.println(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        WorkAddress = new javax.swing.JLabel();
        WorkNumber = new javax.swing.JLabel();
        WorkNumberField = new javax.swing.JTextField();
        YesButton = new javax.swing.JRadioButton();
        NoButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        WorkAddressArea = new javax.swing.JTextArea();
        CurrentHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Institution = new javax.swing.JLabel();
        InstitutionField = new javax.swing.JTextField();
        Grade = new javax.swing.JLabel();
        GradeComboBox = new javax.swing.JComboBox();
        Working = new javax.swing.JLabel();
        WorkPlace = new javax.swing.JLabel();
        WorkPlaceField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CurrentHeading1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WorkAddress.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkAddress.setText("Work-Address");

        WorkNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkNumber.setText("Work-Number");

        WorkNumberField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        WorkNumberField.setText("0");
        WorkNumberField.setEnabled(false);
        WorkNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                WorkNumberFieldFocusLost(evt);
            }
        });

        buttonGroup1.add(YesButton);
        YesButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        YesButton.setText("Yes");
        YesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(NoButton);
        NoButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NoButton.setSelected(true);
        NoButton.setText("No");
        NoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoButtonActionPerformed(evt);
            }
        });

        WorkAddressArea.setColumns(20);
        WorkAddressArea.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkAddressArea.setRows(5);
        WorkAddressArea.setText("None");
        WorkAddressArea.setEnabled(false);
        jScrollPane2.setViewportView(WorkAddressArea);

        CurrentHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading.setText("Current Details");

        jSeparator1.setAlignmentX(1.0F);

        Institution.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Institution.setText("Institution");

        InstitutionField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N

        Grade.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Grade.setText("Grade/Year");

        GradeComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        GradeComboBox.setMaximumRowCount(5);
        GradeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Empty>", "6th", "7th", "8th", "9th", "10th", "11th", "12th", "1st Year", "2nd Year", "3rd Year" }));

        Working.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Working.setText("Working");

        WorkPlace.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkPlace.setText("Work-Place");

        WorkPlaceField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        WorkPlaceField.setText("None");
        WorkPlaceField.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jButton1.setText("Save & Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CurrentHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentHeading1.setText("Empty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Institution, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Working, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WorkNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WorkPlace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WorkAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(Grade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InstitutionField)
                                .addComponent(GradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(YesButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(NoButton))
                                .addComponent(WorkPlaceField)
                                .addComponent(jScrollPane2)
                                .addComponent(WorkNumberField))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(CurrentHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Institution)
                    .addComponent(InstitutionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade)
                    .addComponent(GradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Working)
                    .addComponent(YesButton)
                    .addComponent(NoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkPlace)
                    .addComponent(WorkPlaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(WorkAddress)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesButtonActionPerformed
        // TODO add your handling code here:

        WorkingCondition = "Yes";

        WorkPlaceField.setEnabled(true);
        WorkAddressArea.setEnabled(true);
        WorkNumberField.setEnabled(true);
    }//GEN-LAST:event_YesButtonActionPerformed

    private void NoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoButtonActionPerformed
        // TODO add your handling code here:

        WorkingCondition = "No";
        WorkPlaceField.setText("None");
        WorkAddressArea.setText("None");
        WorkNumberField.setText("0");

        WorkPlaceField.setEnabled(false);
        WorkAddressArea.setEnabled(false);
        WorkNumberField.setEnabled(false);
    }//GEN-LAST:event_NoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    int check = 0;
        
    if(InstitutionField.getText().equals(""))
    {
        Error = new InvalidData();
        Error.setVisible(true);
    }

    else
    {
        if(GradeComboBox.getSelectedItem().equals("<Empty>"))
        {
            Error = new InvalidData();
            Error.setVisible(true);
        }
        
        else
        {
            if(NoButton.isSelected())
                check = 1;
            
            else
            {
                if((WorkPlace.getText().equals("None")) || (WorkPlace.getText().equals("")))
                {
                    Error = new InvalidData();
                    Error.setVisible(true);
                }
                
                else
                {
                    if((WorkAddressArea.getText().equals("None")) || (WorkAddressArea.getText().equals("")))
                    {
                        Error = new InvalidData();
                        Error.setVisible(true);
                    }
                    
                    else
                    {
                        if((WorkNumberField.getText().equals("0")) || (WorkNumberField.getText().equals("")))
                        {
                            Error = new InvalidData();
                            Error.setVisible(true);
                        }
                        
                        else
                            check = 1;
                    }    
                }
            }
        }
    }    
        
    if(check == 1)
    {
        try
        {
            String query = "DELETE FROM CDetails WHERE(ChildName = '" + name + "');";
            stmnt.executeUpdate(query);

            System.out.println("DELETE DONE!");

            query = "INSERT INTO CDetails VALUES('" + name + "', '" + InstitutionField.getText() + "', '" + GradeComboBox.getSelectedItem() + "', '" + WorkingCondition
                + "', '" + WorkPlaceField.getText() + "', '" + WorkAddressArea.getText() + "', " + WorkNumberField.getText() + ");";

            stmnt.executeUpdate(query);
            System.out.println("Save DONE!");

        }

        catch(SQLException b)
        {
            System.out.println("Error");
            System.out.println(b);
        }

        this.setVisible(false);
    }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void WorkNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WorkNumberFieldFocusLost
    
    if(WorkNumberField.getText().equals(""))
        Worknumber = "";
    
    else
    {
        try
        {
            Worknumber = WorkNumberField.getText();
            long p = Integer.parseInt(Worknumber);
        }
        
        catch(NumberFormatException a)
        {
            System.out.println("The Worknumber format is wrong.");
            Error.setVisible(true);
            WorkNumberField.setText("");
        }
        
        Worknumber = WorkNumberField.getText();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkNumberFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterCurrentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentHeading;
    private javax.swing.JLabel CurrentHeading1;
    private javax.swing.JLabel Grade;
    private javax.swing.JComboBox GradeComboBox;
    private javax.swing.JLabel Institution;
    private javax.swing.JTextField InstitutionField;
    private javax.swing.JRadioButton NoButton;
    private javax.swing.JLabel WorkAddress;
    private javax.swing.JTextArea WorkAddressArea;
    private javax.swing.JLabel WorkNumber;
    private javax.swing.JTextField WorkNumberField;
    private javax.swing.JLabel WorkPlace;
    private javax.swing.JTextField WorkPlaceField;
    private javax.swing.JLabel Working;
    private javax.swing.JRadioButton YesButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
