/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

/**
 *
 * @author hp
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class DeletePerson extends javax.swing.JFrame {

    /**
     * Creates new form DeletePerson
     */
    
    ResultSet resultSet;
    String[] NameList = new String[15];
    String framename;
    String name;
    Statement stmnt;
    
    public DeletePerson() {
        initComponents();
        
        DeleteField.setEnabled(false);
        
        try
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
            }
            
            catch(ClassNotFoundException a)
            {
                System.out.println("Error class not Found");
            }
            
            String userID = "root";
            String password = "iamshlok";
            String URL = "jdbc:mysql://localhost:3306/hostel";
            
            Connection connect = DriverManager.getConnection(URL, userID, password);
            stmnt = connect.createStatement();
            
            System.out.println("Connection Established!");
            
            String query = "SELECT * FROM PDetails;";
            resultSet = stmnt.executeQuery(query);
            
            int c = 0;
            NameComboBox.addItem("<Empty>");
            while(resultSet.next())
            {
                NameList[c] = resultSet.getString("PersonName");
                
                System.out.println("Name: " + NameList[c]);
                NameComboBox.addItem(NameList[c]);
                
                c++;
            }
        }
        
        catch(SQLException a)
        {
            System.out.println(a);
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadDetailsHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NameLabel = new javax.swing.JLabel();
        NameComboBox = new javax.swing.JComboBox<>();
        DeleteRadioButton = new javax.swing.JRadioButton();
        DeleteField = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoadDetailsHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        LoadDetailsHeading.setText("Delete Data");

        jSeparator1.setAlignmentX(1.0F);

        NameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        NameLabel.setText("Name");

        NameComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        NameComboBox.setMaximumRowCount(15);
        NameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameComboBoxActionPerformed(evt);
            }
        });

        DeleteRadioButton.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        DeleteRadioButton.setText("Delete");
        DeleteRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRadioButtonActionPerformed(evt);
            }
        });

        DeleteField.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        DeleteField.setText("Delete");
        DeleteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoadDetailsHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(DeleteField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoadDetailsHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteField)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameComboBoxActionPerformed
        // TODO add your handling code here:
        name = (String)NameComboBox.getSelectedItem();
        if(name.equals("<Empty>"))
        {
                DeleteField.setEnabled(false);
                DeleteRadioButton.setEnabled(false);
        } 
        
        else
            DeleteRadioButton.setEnabled(true);
    }//GEN-LAST:event_NameComboBoxActionPerformed

    private void DeleteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFieldActionPerformed
        // TODO add your handling code here:
        
        if(DeleteRadioButton.isSelected())
        {
            try
            {
                String query1 = "DELETE FROM PDetails WHERE(personName = '" + name + "');";
                String query2 = "DELETE FROM FDetails WHERE(personName = '" + name + "');";
                String query3 = "DELETE FROM HostelDetails WHERE(personName = '" + name + "');";
                String query4 = "DELETE FROM CDetails WHERE(ChildName = '" + name + "');";
                String query5 = "DELETE FROM LocationDetails WHERE(personName = '" + name + "');";
                
                ResultSet rs;
                
                String query6 = "SELECT * FROM HostelDetails WHERE(personName = '" + name + "');";
                rs = stmnt.executeQuery(query6);
                
                rs.next();
                
                query6 = "UPDATE RoomInfo SET " + rs.getString(5) + " = 0 WHERE(Room = '" + rs.getString(2) + "');";
                
                stmnt.executeUpdate(query6);
                stmnt.executeUpdate(query1);
                stmnt.executeUpdate(query2);
                stmnt.executeUpdate(query3);
                stmnt.executeUpdate(query4);
                stmnt.executeUpdate(query5);
            
                this.setVisible(false);
            }
            
            catch (SQLException a)
            {
                System.out.println("Error");
                System.out.println(a);
            }
        }
        
        else
        {
            
        }
    }//GEN-LAST:event_DeleteFieldActionPerformed

    private void DeleteRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRadioButtonActionPerformed
        // TODO add your handling code here:
        
        if(DeleteRadioButton.isSelected())
        {
            DeleteField.setEnabled(true);
        }
        
        else
        {
            DeleteField.setEnabled(false);
        }
    }//GEN-LAST:event_DeleteRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePerson().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteField;
    private javax.swing.JRadioButton DeleteRadioButton;
    private javax.swing.JLabel LoadDetailsHeading;
    private javax.swing.JComboBox<String> NameComboBox;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
 }
