/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

/**
 *
 * @author hp
 */

import static hostel.EntryForm2.Error;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class EntryForm5 extends javax.swing.JFrame {

    /**
     * Creates new form EntryForm5
     */
    
    public static EntryForm6 f1;
    public static String InstitutionName;
    public static String Standard;
    public static String WorkingCondition;
    public static String Workplace;
    public static String Workaddress;
    public static String Worknumber;
    public static InvalidData Error = new InvalidData();
    
    public EntryForm5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        CurrentHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Institution = new javax.swing.JLabel();
        InstitutionField = new javax.swing.JTextField();
        Grade = new javax.swing.JLabel();
        GradeComboBox = new javax.swing.JComboBox();
        Working = new javax.swing.JLabel();
        WorkPlace = new javax.swing.JLabel();
        WorkPlaceField = new javax.swing.JTextField();
        WorkAddress = new javax.swing.JLabel();
        WorkNumber = new javax.swing.JLabel();
        WorkNumberField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        YesButton = new javax.swing.JRadioButton();
        NoButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        WorkAddressArea = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entry Form");
        setResizable(false);

        CurrentHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading.setText("Current Details");

        jSeparator1.setAlignmentX(1.0F);

        Institution.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Institution.setText("Institution");

        InstitutionField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N

        Grade.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Grade.setText("Grade/Year");

        GradeComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        GradeComboBox.setMaximumRowCount(5);
        GradeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Empty>", "6th", "7th", "8th", "9th", "10th", "11th", "12th", "1st Year", "2nd Year", "3rd Year" }));

        Working.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Working.setText("Working");

        WorkPlace.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkPlace.setText("Work-Place");

        WorkPlaceField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        WorkPlaceField.setText("None");
        WorkPlaceField.setDragEnabled(true);
        WorkPlaceField.setEnabled(false);

        WorkAddress.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkAddress.setText("Work-Address");

        WorkNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkNumber.setText("Work-Number(0731)");

        WorkNumberField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        WorkNumberField.setText("0");
        WorkNumberField.setEnabled(false);
        WorkNumberField.setFocusable(true);
        WorkNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                WorkNumberFieldFocusLost(evt);
            }
        });

        SaveButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(YesButton);
        YesButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        YesButton.setText("Yes");
        YesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(NoButton);
        NoButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NoButton.setSelected(true);
        NoButton.setText("No");
        NoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoButtonActionPerformed(evt);
            }
        });

        WorkAddressArea.setColumns(20);
        WorkAddressArea.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkAddressArea.setRows(5);
        WorkAddressArea.setText("None");
        WorkAddressArea.setEnabled(false);
        jScrollPane2.setViewportView(WorkAddressArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Institution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CurrentHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Grade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Working, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WorkPlaceField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(InstitutionField)
                    .addComponent(WorkNumberField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YesButton)
                                .addGap(18, 18, 18)
                                .addComponent(NoButton)))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CurrentHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Institution)
                    .addComponent(InstitutionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grade)
                    .addComponent(GradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Working)
                    .addComponent(YesButton)
                    .addComponent(NoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkPlace)
                    .addComponent(WorkPlaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WorkAddress)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
    
    Worknumber = WorkNumberField.getText(); 
    InstitutionName = InstitutionField.getText();
    Standard = (String)GradeComboBox.getSelectedItem();
    Workaddress = WorkAddressArea.getText();
    Workplace = WorkPlaceField.getText();    
    int check = 0;
    
    if(InstitutionField.getText().equals(""))
    {
        Error = new InvalidData();
        Error.setVisible(true);
    }
    
    else
    {
        if(GradeComboBox.getSelectedItem().equals("<Empty>"))
        {
               Error = new InvalidData();
               Error.setVisible(true);
        }
        
        else
        {
            if(NoButton.isSelected())
                check = 1;
            
            else
            {
                if((WorkPlaceField.getText().equals("None")) || (WorkPlaceField.getText().equals("")))
                {
                    Error = new InvalidData();
                    Error.setVisible(true);
                }
                
                else
                {
                    if((WorkAddressArea.getText().equals("None")) || (WorkAddressArea.getText().equals("")))
                    {
                        Error = new InvalidData();
                        Error.setVisible(true);
                    }
                    
                    else
                    {
                        if((WorkNumberField.getText().equals("")) || (WorkNumberField.getText().equals("0")))
                        {
                            Error = new InvalidData();
                            Error.setVisible(true);
                        }
                        
                        else
                            check = 1;
                    }
                }
            }
        }
    }
    
    if(check == 1)
    {
        try
            {
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                }
            
                catch(ClassNotFoundException e)
                {
                    System.out.println("No such class");
                }
        
                String UserID = "root";
                String Password = "iamshlok";
                String DB_URL = "jdbc:mysql://localhost:3306/hostel";
        
                Connection conn = DriverManager.getConnection(DB_URL, UserID, Password);
                Statement stmnt = conn.createStatement();
            
                System.out.println("Connection Established");
            
                String query = "INSERT INTO PDetails VALUES('" + EntryForm2.Name + "', " + EntryForm2.ID + ", '"+ EntryForm2.BGroup + 
                "'," + EntryForm2.PhoneNumber + ", '" + EntryForm2.Date + "', '" + EntryForm2.Diseases + "');";
            
                String query2 = "INSERT INTO FDetails VALUES ('" + EntryForm2.Name + "', '" + EntryForm3.Fname + "', '" + EntryForm3.Mname + "', "
                + EntryForm3.Mnumber + ", " + EntryForm3.Fnumber + ", '" + EntryForm3.Address + "', " + EntryForm3.Landline + ");";        

                String query3 = "INSERT INTO LocationDetails VALUES ('" + EntryForm2.Name + "', '" + EntryForm4.StateName + "', '" 
                + EntryForm4.CityName + "', " + EntryForm4.Pincode + ");";

                String query4 = "INSERT INTO CDetails VALUES ('" + EntryForm2.Name + "', '" + InstitutionName + "', '" 
                + Standard + "', '" + WorkingCondition + "', '" + Workplace + "', '" + Workaddress + "', " + Worknumber + ");";

                String query5 = "INSERT INTO HostelDetails VALUES ('" + EntryForm2.Name + "', '" + EntryForm6.RoomNo + "', " + EntryForm6.CautionMoney
                + ", " + EntryForm6.Fees + ", '" + EntryForm6.person + "');";

                String query6 = "UPDATE RoomInfo SET " + EntryForm6.person + " = " + EntryForm2.ID + " WHERE(Room = '" + EntryForm6.Roomno + "');";

                System.out.println(query5);

                stmnt.executeUpdate(query);
                System.out.println("PDetails Done");
            
                stmnt.executeUpdate(query2);
                System.out.println("FDetails Done");

                stmnt.executeUpdate(query3);
                System.out.println("LocationDetails Done");

                stmnt.executeUpdate(query4);
                System.out.println("CDetails Done");

                stmnt.executeUpdate(query5);
                System.out.println("HostelDetails Done");

                stmnt.executeUpdate(query6);
                System.out.println("Room Updates Done");

                this.setVisible(false);
            }

            catch(SQLException a)
            {
                System.out.println("SQL Exception");
                System.out.println(a);
            }

            this.setVisible(false);
        }    
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void YesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesButtonActionPerformed
        // TODO add your handling code here:
        
        WorkingCondition = "Yes";
        
        WorkPlaceField.setEnabled(true);
        WorkAddressArea.setEnabled(true);
        WorkNumberField.setEnabled(true);
        WorkNumberField.setEditable(true);
    }//GEN-LAST:event_YesButtonActionPerformed

    private void NoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoButtonActionPerformed
        // TODO add your handling code here:
        
        WorkingCondition = "No";
        WorkPlaceField.setText("None");
        WorkAddressArea.setText("None");
        WorkNumberField.setText("0");
        
        WorkPlaceField.setEnabled(false);
        WorkAddressArea.setEnabled(false);
        WorkNumberField.setEnabled(false);
    }//GEN-LAST:event_NoButtonActionPerformed

    private void WorkNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WorkNumberFieldFocusLost
        // TODO add your handling code here:
    if(WorkNumberField.getText().equals(""))
        Worknumber = "";
    
    else
    {
        try
        {
            Worknumber = WorkNumberField.getText();
            long p = Integer.parseInt(Worknumber);
        }
        
        catch(NumberFormatException a)
        {
            System.out.println("The Worknumber format is wrong.");
            Error = new InvalidData();
            Error.setVisible(true);
            WorkNumberField.setText("");
        }
        
        Worknumber = WorkNumberField.getText();
    }
    }//GEN-LAST:event_WorkNumberFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentHeading;
    private javax.swing.JLabel Grade;
    private javax.swing.JComboBox GradeComboBox;
    private javax.swing.JLabel Institution;
    private javax.swing.JTextField InstitutionField;
    private javax.swing.JRadioButton NoButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel WorkAddress;
    private javax.swing.JTextArea WorkAddressArea;
    private javax.swing.JLabel WorkNumber;
    private javax.swing.JTextField WorkNumberField;
    private javax.swing.JLabel WorkPlace;
    private javax.swing.JTextField WorkPlaceField;
    private javax.swing.JLabel Working;
    private javax.swing.JRadioButton YesButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
