/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

import static hostel.EntryForm2.Error;

/**
 *
 * @author hp
 */
public class EntryForm3 extends javax.swing.JFrame {

    /**
     * Creates new form EntryForm3
     */
    
    public static EntryForm4 f2;
    
    public static String Fname;
    public static String Fnumber;
    
    public static String Mname;
    public static String Mnumber;
    
    public static String Landline;
    public static String Address;
    public static InvalidData Error; 
            
    public EntryForm3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FamilyHeading = new javax.swing.JLabel();
        FatherName = new javax.swing.JLabel();
        FatherNameField = new javax.swing.JTextField();
        MotherName = new javax.swing.JLabel();
        MotherNameField = new javax.swing.JTextField();
        FatherNumber = new javax.swing.JLabel();
        MotherNumber = new javax.swing.JLabel();
        LandlineNumberField = new javax.swing.JTextField();
        Adress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();
        LandlineNumber = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        FatherNumberField = new javax.swing.JTextField();
        MotherNumberField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entry Form");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        jSeparator1.setAlignmentX(1.0F);

        FamilyHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        FamilyHeading.setText("Family Details");

        FatherName.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        FatherName.setText("Father's Name");

        FatherNameField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        FatherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameFieldActionPerformed(evt);
            }
        });

        MotherName.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        MotherName.setText("Mother's Name");

        MotherNameField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        MotherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherNameFieldActionPerformed(evt);
            }
        });

        FatherNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        FatherNumber.setText("Father's Number");

        MotherNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        MotherNumber.setText("Mother's Number");

        LandlineNumberField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        LandlineNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LandlineNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LandlineNumberFieldFocusLost(evt);
            }
        });
        LandlineNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LandlineNumberFieldActionPerformed(evt);
            }
        });

        Adress.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Adress.setText("Address");

        AddressTextArea.setColumns(20);
        AddressTextArea.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        AddressTextArea.setRows(5);
        jScrollPane1.setViewportView(AddressTextArea);

        LandlineNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        LandlineNumber.setText("Landline Number (0731)");

        NextButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        FatherNumberField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        FatherNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FatherNumberFieldFocusLost(evt);
            }
        });

        MotherNumberField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        MotherNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                MotherNumberFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(LandlineNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LandlineNumberField)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FamilyHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FatherNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FatherNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(MotherNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(FatherNumberField)
                                    .addComponent(MotherNumberField))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Adress, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FamilyHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FatherNumber)
                            .addComponent(FatherNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MotherNumber)
                            .addComponent(MotherNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FatherName))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MotherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherName))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Adress)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LandlineNumber)
                            .addComponent(LandlineNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FatherNameFieldActionPerformed

    private void MotherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotherNameFieldActionPerformed

    private void LandlineNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LandlineNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LandlineNumberFieldActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        Fname = FatherNameField.getText();
        Mname = MotherNameField.getText();
        Address = AddressTextArea.getText();
        Fnumber = FatherNumberField.getText();
        Mnumber = MotherNumberField.getText();
        
        Error = new InvalidData();
        
        if(Fname.equals(""))
        {
               Error = new InvalidData();
               Error.setVisible(true);
        }
        
        else
        {
            if(Mname.equals(""))
            {
               Error = new InvalidData();
               Error.setVisible(true);
            }
            
            else
            {
                if(Address.equals(""))
                {
                    Error = new InvalidData();
                    Error.setVisible(true);
                }
                
                else
                {
                    if(Mnumber.equals(""))
                    {
                        Error = new InvalidData();
                        Error.setVisible(true);
                    }
                    
                    else
                    {
                        if(Fnumber.equals(""))
                        {
                            Error = new InvalidData();
                            Error.setVisible(true);
                        }
                        
                        else
                        {
                            if(Landline.equals(""))
                            {
                                Error = new InvalidData();
                                Error.setVisible(true);
                            }
                            
                            else
                            { 
                                f2 = new EntryForm4();
                                this.setVisible(false);
                                f2.setVisible(true);
        
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_NextButtonActionPerformed

    private void LandlineNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LandlineNumberFieldFocusLost
        // TODO add your handling code here:
        if(LandlineNumberField.getText().equals(""))
            Landline = "";
 
        else
        {
            try
            {
                Landline = LandlineNumberField.getText();
                int p = Integer.parseInt(Landline);
            }

            catch(NumberFormatException a)
            {
                System.out.println("The Format is wrong");
                LandlineNumberField.setText("");
                Error = new InvalidData();
                Error.setVisible(true);
            }
            Landline = LandlineNumberField.getText();
        }    
    }//GEN-LAST:event_LandlineNumberFieldFocusLost

    private void LandlineNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LandlineNumberFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LandlineNumberFieldFocusGained

    private void FatherNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherNumberFieldFocusLost
        // TODO add your handling code here:
        if(FatherNumberField.getText().equals(""))
            Fnumber = "";
        
        else
        {
            try
            {
                Fnumber = FatherNumberField.getText();
                long p = Long.parseLong(Fnumber);
            }

            catch(NumberFormatException a)
            {
                System.out.println("The Father Number Format is wrong");
                Error = new InvalidData();
                Error.setVisible(true);
                FatherNumberField.setText("");
            }
            
            Fnumber = FatherNumberField.getText();
        }    
    }//GEN-LAST:event_FatherNumberFieldFocusLost

    private void MotherNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherNumberFieldFocusLost
        // TODO add your handling code here:
        if(MotherNumberField.getText().equals(""))
            Mnumber = "";
        
        else
        {

            try
            {
                Mnumber = MotherNumberField.getText();
                long p = Long.parseLong(Mnumber);
            }

            catch(NumberFormatException a)
            {
                System.out.println("The Father Number Format is wrong");
                Error = new InvalidData();
                Error.setVisible(true);
                MotherNumberField.setText("");
            }
        }
        
        Mnumber = MotherNumberField.getText();
    }//GEN-LAST:event_MotherNumberFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JLabel Adress;
    private javax.swing.JLabel FamilyHeading;
    private javax.swing.JLabel FatherName;
    private javax.swing.JTextField FatherNameField;
    private javax.swing.JLabel FatherNumber;
    private javax.swing.JTextField FatherNumberField;
    private javax.swing.JLabel LandlineNumber;
    private javax.swing.JTextField LandlineNumberField;
    private javax.swing.JLabel MotherName;
    private javax.swing.JTextField MotherNameField;
    private javax.swing.JLabel MotherNumber;
    private javax.swing.JTextField MotherNumberField;
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
