/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hp
 */

public class EntryForm2 extends javax.swing.JFrame
{     
    public static String Name;
    public static int ID;
    public static String PhoneNumber;
    public static String Diseases;
    public static Date DOB = new Date();
    public static String Date;
    public static Date empty = new Date();
    public static String BGroup; 
    public static EntryForm3 f1;     
    public static InvalidData Error;
    public static long p;
    /**
     * Creates new form Entry
     */
    public EntryForm2() {
        initComponents();
        
        try
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
            }
            
            catch(ClassNotFoundException e)
            {
                System.out.println("No such class");
            }
        
            String UserID = "root";
            String Password = "iamshlok";
            String DB_URL = "jdbc:mysql://localhost:3306/hostel";
        
            Connection conn = DriverManager.getConnection(DB_URL, UserID, Password);
            Statement stmnt = conn.createStatement();
            
            System.out.println("Connection Established");
            
            String query = "SELECT * FROM PDetails;";
            ResultSet rs = stmnt.executeQuery(query);
            
            ID = 1;
            while(rs.next())
            {
                ID++;
            }
            
            String id;
            id = Integer.toString(ID);
            
            PersonIDField.setText(id);
        }
        
        catch(SQLException a)
        {
            System.out.println("SQL Exception");
            System.out.println(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        PersonalHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PersonName = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        PersonDOB = new javax.swing.JLabel();
        PersonNumber = new javax.swing.JLabel();
        NumberField = new javax.swing.JTextField();
        PersonDisease = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DiseasesArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BloodGroup = new javax.swing.JLabel();
        BloodComboBox = new javax.swing.JComboBox();
        PersonIDHeading = new javax.swing.JLabel();
        PersonIDField = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("jLabel6");

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entry Form");
        setResizable(false);

        PersonalHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        PersonalHeading.setText("Personal Details");

        jSeparator1.setAlignmentX(1.0F);

        PersonName.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName.setText("Name");

        NameField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        PersonDOB.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonDOB.setText("Date of Birth");

        PersonNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonNumber.setText("Phone Number");

        NumberField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumberFieldFocusLost(evt);
            }
        });
        NumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberFieldActionPerformed(evt);
            }
        });

        PersonDisease.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonDisease.setText("Diseases");

        DiseasesArea.setColumns(20);
        DiseasesArea.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        DiseasesArea.setRows(5);
        DiseasesArea.setText("None");
        jScrollPane2.setViewportView(DiseasesArea);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N

        NextButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        BloodGroup.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        BloodGroup.setText("Blood Group");

        BloodComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        BloodComboBox.setMaximumRowCount(5);
        BloodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Empty>", "A+", "O+", "B+", "AB+", "A-", "O-", "B-", "AB-" }));

        PersonIDHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonIDHeading.setText("Person ID");

        PersonIDField.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonIDField.setText("Empty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonIDHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PersonIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PersonName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PersonDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PersonNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PersonDisease, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(BloodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NumberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PersonalHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PersonalHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonIDHeading)
                    .addComponent(PersonIDField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodGroup)
                    .addComponent(BloodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PersonDOB)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PersonDisease)
                        .addGap(43, 43, 43)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
       
       BGroup = (String)BloodComboBox.getSelectedItem();
       
       DOB = jXDatePicker1.getDate();
       Name = NameField.getText();
       
       Diseases = DiseasesArea.getText();
       
       String dat = "";
       
       try
       {
            dat = DOB.toString();
       }
       
       catch(NullPointerException b)
       {
           System.out.println("DOB Field is empty");
           
       }
       
       System.out.println(dat);
        
        if(dat.equals(""));
        
        else
        {
            int year = Integer.parseInt(dat.substring(24));
            String mon;
            int month = 0;
            int day = Integer.parseInt(dat.substring(8,10));
        
            mon = dat.substring(4, 7);
        
            if(mon.equals("Mar"))
                month = 03;
        
            else if(mon.equalsIgnoreCase("Jan"))
                month = 01;
        
            else if(mon.equalsIgnoreCase("Feb"))
                month = 02;
        
            else if(mon.equalsIgnoreCase("Apr"))
                month = 04;
        
            else if(mon.equalsIgnoreCase("May"))
                month = 05;
        
            else if(mon.equalsIgnoreCase("Jun"))
                month = 06;
        
            else if(mon.equalsIgnoreCase("Jul"))
                month = 07;
        
            else if(mon.equalsIgnoreCase("Aug"))
                month = 8;
        
            else if(mon.equalsIgnoreCase("Sep"))
                month = 9;
        
            else if(mon.equalsIgnoreCase("Oct"))
                month = 10;
            
            else if(mon.equalsIgnoreCase("Nov"))
                month = 11;
        
            else if(mon.equalsIgnoreCase("Dec"))
                month = 12;
        
        
            System.out.println(day);
            Date = year + "-" + month + "-" + day; 
        
            System.out.println(Date);
        }
        
        Error = new InvalidData(); 
        
       if(Name.equals(""))
           Error.setVisible(true);
       else
       {
           if(BloodComboBox.getSelectedItem().equals("<Empty>"))
           {
               Error = new InvalidData();
               Error.setVisible(true);
           }
           else
           {
               if(PhoneNumber.equals(""))
               {
                   Error = new InvalidData();
                   Error.setVisible(true);
               }
               
               else
               {
                   if(dat.equals(""))
                   {
                        Error = new InvalidData();
                        Error.setVisible(true);
                   }
                   
                   else
                   {
                        f1 = new EntryForm3();
                        f1.setVisible(true);
                        this.setVisible(false);    
                   }
               }
           }
       } 
    }//GEN-LAST:event_NextButtonActionPerformed

    private void NumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberFieldActionPerformed

    private void NumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberFieldFocusLost
       // TODO add your handling code here:
        if(NumberField.getText().equals(""))
            PhoneNumber = "";
        else
        {
            try
            {
                PhoneNumber = NumberField.getText();               
                p = Long.parseLong(PhoneNumber);
            }
       
            catch(NumberFormatException a)
            {
                System.out.println("The phone number field has invalid data.");
                NumberField.setText("");
                Error = new InvalidData();
                Error.setVisible(true);
            }
            
            System.out.println("NumberField: " + NumberField.getText());
            PhoneNumber = NumberField.getText();       
        } 
    }//GEN-LAST:event_NumberFieldFocusLost

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BloodComboBox;
    private javax.swing.JLabel BloodGroup;
    private javax.swing.JTextArea DiseasesArea;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton NextButton;
    private javax.swing.JTextField NumberField;
    private javax.swing.JLabel PersonDOB;
    private javax.swing.JLabel PersonDisease;
    private javax.swing.JLabel PersonIDField;
    private javax.swing.JLabel PersonIDHeading;
    private javax.swing.JLabel PersonName;
    private javax.swing.JLabel PersonNumber;
    private javax.swing.JLabel PersonalHeading;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
