/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

/**
 *
 * @author hp
 */

import static hostel.EntryForm2.Error;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class EntryForm6 extends javax.swing.JFrame {

    /**
     * Creates new form EntryForm6
     */
    
    EntryForm5 f2;
    InvalidData Error = new InvalidData();
    public static String Fees;
    public static String CautionMoney;
    public static String RoomNo;
    public static String selectedRoom;
    public static ResultSet resultSet;
    public static String Roomno;
    public static String person;
    NoSpace f4;
    
    public EntryForm6() {
        initComponents();
    
    }    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        CurrentHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RoomNumberHeading = new javax.swing.JLabel();
        RoomNumberHeading1 = new javax.swing.JLabel();
        FeesField = new javax.swing.JTextField();
        CautionField = new javax.swing.JTextField();
        CautionHeading = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        RoomComboBox = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CurrentHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading.setText("Hostel Details");

        jSeparator1.setAlignmentX(1.0F);

        RoomNumberHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        RoomNumberHeading.setText("Room Number");

        RoomNumberHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        RoomNumberHeading1.setText("Fees");

        FeesField.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        FeesField.setText("0");
        FeesField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FeesFieldFocusLost(evt);
            }
        });
        FeesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeesFieldActionPerformed(evt);
            }
        });

        CautionField.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        CautionField.setText("0");
        CautionField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CautionFieldFocusLost(evt);
            }
        });
        CautionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautionFieldActionPerformed(evt);
            }
        });

        CautionHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        CautionHeading.setText("Caution Money");

        NextButton.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        RoomComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        RoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Empty>", "Ground - 1", "Ground - 2", "Ground - 3", "First - 1", "First - 2", "First - 3" }));
        RoomComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RoomComboBoxFocusLost(evt);
            }
        });
        RoomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CautionHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RoomNumberHeading1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RoomNumberHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CurrentHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(CautionField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(FeesField)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RoomComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomNumberHeading)
                    .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomNumberHeading1)
                    .addComponent(FeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CautionHeading)
                    .addComponent(CautionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CautionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CautionFieldActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
            
        if((RoomComboBox.getSelectedItem()).equals("<Empty>"))
        {
            Error = new InvalidData();
            Error.setVisible(true);
        }
        
        else
        {
            if((FeesField.getText()).equals("0") || (FeesField.getText()).equals(""))
            {
               Error = new InvalidData();
               Error.setVisible(true);
            }
            
            else
            {
                if(CautionField.getText().equals("0") || (CautionField.getText()).equals(""))
                {
                    Error = new InvalidData();
                    Error.setVisible(true);
                }
                
                else
                {
                    Fees = FeesField.getText();
                    CautionMoney = CautionField.getText();
        
                    f2 = new EntryForm5();
        
                    this.setVisible(false);
                    f2.setVisible(true);
        
                }
            }
        }
    }//GEN-LAST:event_NextButtonActionPerformed

    private void RoomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomComboBoxActionPerformed
        // TODO add your handling code here:
        
        selectedRoom = (String)RoomComboBox.getSelectedItem();
        
        if(selectedRoom.equals("<Empty>"))
            NextButton.setEnabled(false);
        
        else
        {   
            try
            {
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                }
            
                catch(ClassNotFoundException a)
                {
                    System.out.println("Error class not Found");
                }
            
                String userID = "root";
                String password = "iamshlok";
                String URL = "jdbc:mysql://localhost:3306/hostel";
            
                Connection connect = DriverManager.getConnection(URL, userID, password);
                Statement stmnt = connect.createStatement();

                System.out.println("Connection Established!");
                Roomno = "Empty";
                String query;

                query = "SELECT * FROM RoomInfo WHERE(Room = '" + selectedRoom + "');";
                resultSet = stmnt.executeQuery(query);
                
                resultSet.next();
                String Available = "NO";
                
                int noofp = resultSet.getInt(3);
                
                if(resultSet.getInt(4) == 0)
                {
                    person = "Person1";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }
                
                else if(resultSet.getInt(5) == 0 && Available.equals("NO"))
                {
                    person = "Person2";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }
                
                else if(resultSet.getInt(6) == 0 && Available.equals("NO") && resultSet.getString(1).equals("First - 3"))
                {
                    person = "Person3";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }
                
                else if(resultSet.getInt(7) == 0 && Available.equals("NO") && resultSet.getString(1).equals("First - 3"))
                {
                    person = "Person4";
                    Roomno = resultSet.getString(1);
                    Available = "YES";
                }
                
                if(Available.equals("YES"))
                {
                   RoomNo = Roomno;
                   NextButton.setEnabled(true);
                }
                
                else
                {
                    NextButton.setEnabled(false);
                    RoomComboBox.setSelectedItem("<Empty>");
                    f4 = new NoSpace();
                    
                    f4.setVisible(true);
                }
            }
            catch(SQLException a)
            {
                System.out.println("Error");
                System.out.println(a);
            }
        }    
    }//GEN-LAST:event_RoomComboBoxActionPerformed

    private void RoomComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RoomComboBoxFocusLost
        // TODO add your handling code here:        
    }//GEN-LAST:event_RoomComboBoxFocusLost

    private void FeesFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FeesFieldFocusLost
        // TODO add your handling code here:
    if(FeesField.getText().equals(""))
        Fees = "";
        
    else
    {
        try
        {
            Fees = FeesField.getText();
            long p = Integer.parseInt(Fees);
        }
        
        catch(NumberFormatException a)
        {
            System.out.println("The Number Format of Fees is invalid.");
            FeesField.setText("");
            Error = new InvalidData();
            Error.setVisible(true);
        }
        
        Fees = FeesField.getText();
    }    
    }//GEN-LAST:event_FeesFieldFocusLost

    private void CautionFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CautionFieldFocusLost
        // TODO add your handling code here:
    if(CautionField.getText().equals(""))
        CautionMoney = "";
    else
    {
        try
        {
            CautionMoney = CautionField.getText();
            long p = Integer.parseInt(CautionMoney);
        }
        
        catch(NumberFormatException a)
        {
            System.out.println("The number format of the Caution Money is wrong.");
            Error = new InvalidData();
            Error.setVisible(true);
            CautionField.setText("");
        }
        
        CautionMoney = CautionField.getText();
    }    
    }//GEN-LAST:event_CautionFieldFocusLost

    private void FeesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CautionField;
    private javax.swing.JLabel CautionHeading;
    private javax.swing.JLabel CurrentHeading;
    private javax.swing.JTextField FeesField;
    private javax.swing.JButton NextButton;
    private javax.swing.JComboBox<String> RoomComboBox;
    private javax.swing.JLabel RoomNumberHeading;
    private javax.swing.JLabel RoomNumberHeading1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
