/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

import static hostel.EntryForm2.Error;

/**
 *
 * @author hp
 */
public class EntryForm4 extends javax.swing.JFrame {

    /**
     * Creates new form EntryForm4
     */
    public EntryForm4() {
        initComponents();
    }
    
    public static InvalidData Error = new InvalidData();
    public static EntryForm6 f2;
    public static String StateName;
    public static String CityName;
    public static String Pincode;
    
    int check = 0;
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        LocationHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        State = new javax.swing.JLabel();
        StateComboBox = new javax.swing.JComboBox();
        City = new javax.swing.JLabel();
        PinCode = new javax.swing.JLabel();
        PinCodeField = new javax.swing.JTextField();
        NextButton1 = new javax.swing.JButton();
        CityTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entry Form");
        setResizable(false);

        LocationHeading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        LocationHeading.setText("Location");

        jSeparator1.setAlignmentX(1.0F);

        State.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        State.setText("State");

        StateComboBox.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        StateComboBox.setMaximumRowCount(10);
        StateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Empty>", "Jammu And Kashmir", "Haryana", "Punjab", "Uttar Pradesh", "Uttarakhand", "Sikkim", "Arunachal Pradesh", "Assam", "Meghalaya", "Mizoram", "Tripura", "Nagaland", "Manipur", "Madhya Pradesh", "Jharkhand", "Chattisgarh", "Bihar", "West Bengal", "Gujarat", "Rajasthan", "Maharashtra", "Kerela", "Karnataka", "Tamil Nadu", "Telangana", "Andra Pradesh", "Goa", "Delhi" }));
        StateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateComboBoxActionPerformed(evt);
            }
        });

        City.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        City.setText("City");

        PinCode.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PinCode.setText("Pin Code");

        PinCodeField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        PinCodeField.setText("<Empty>");
        PinCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PinCodeFieldFocusLost(evt);
            }
        });

        NextButton1.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        NextButton1.setText("Next");
        NextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton1ActionPerformed(evt);
            }
        });

        CityTextField.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        CityTextField.setText("<Empty>");
        CityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CityTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(State, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LocationHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(City, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PinCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PinCodeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StateComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CityTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LocationHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State)
                    .addComponent(StateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PinCode)
                    .addComponent(PinCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NextButton1)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton1ActionPerformed
        // TODO add your handling code here:
        
        CityName = CityTextField.getText();
        Pincode = PinCodeField.getText();
        
        if((StateComboBox.getSelectedItem()).equals("<Empty>"))
        {
               Error = new InvalidData();
               Error.setVisible(true);
        }
        
        else
        {
            if(CityName.equals("<Empty>") || (CityName.equals("")))
            {
               Error = new InvalidData();
               Error.setVisible(true);
            }
            
            else
            {
                if(Pincode.equals("<Empty>") || (Pincode.equals("")))
                {
                    Error = new InvalidData();
                    Error.setVisible(true);
                }
                
                else
                {
                    f2 = new EntryForm6();
                    this.setVisible(false);
                    f2.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_NextButton1ActionPerformed

    private void StateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateComboBoxActionPerformed
        
       StateName = (String)StateComboBox.getSelectedItem();
       System.out.println(StateName);
       
       check = 1;
    }//GEN-LAST:event_StateComboBoxActionPerformed

    private void PinCodeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PinCodeFieldFocusLost
        // TODO add your handling code here:
    
    if(PinCodeField.getText().equals(""))
        Pincode = "";
    else
    {
        try
        {
            Pincode = PinCodeField.getText();
            int p = Integer.parseInt(Pincode);
        }
        
        catch(NumberFormatException a)
        {
            PinCodeField.setText("");
            System.out.println("The pincode is wrong");
            Error = new InvalidData();
            Error.setVisible(true);
        }
        Pincode = PinCodeField.getText();
    }    
    }//GEN-LAST:event_PinCodeFieldFocusLost

    private void CityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryForm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryForm4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel City;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JLabel LocationHeading;
    private javax.swing.JButton NextButton1;
    private javax.swing.JLabel PinCode;
    private javax.swing.JTextField PinCodeField;
    private javax.swing.JLabel State;
    private javax.swing.JComboBox StateComboBox;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
