/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel;

/**
 *
 * @author hp
 */
import static hostel.LoadPersonalDetails.name;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class LoadCurrentDetails extends javax.swing.JFrame {

    /**
     * Creates new form LoadCurrentDetails
     */
    
    String name;
    
    public LoadCurrentDetails() {
        initComponents();

        name = LoadPerson.Name;
        System.out.println(name);
        CurrentHeading1.setText(name);
        
        try
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
            }
            
            catch(ClassNotFoundException a)
            {
                System.out.println("Error class not Found");
            }
            
            String userID = "root";
            String password = "iamshlok";
            String URL = "jdbc:mysql://localhost:3306/hostel";
            
            Connection connect = DriverManager.getConnection(URL, userID, password);
            Statement stmnt = connect.createStatement();
            
            System.out.println("Connection Established!");
            
            String query = "SELECT * FROM CDetails WHERE(ChildName = '" + name + "');";
            
            ResultSet RS = stmnt.executeQuery(query);
            RS.first();
            
            WorkPlace.setText(RS.getString(5));
            WorkNumber.setText(RS.getString(7));
            Institution.setText(RS.getString(2));
            WorkAddress.setText(RS.getString(6));
            Grade.setText(RS.getString(3));
            Working.setText(RS.getString(4));
            
                      
        }
        catch(SQLException a)
        {
            System.out.println(a);
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonName3 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        PersonName7 = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CurrentHeading1 = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        PersonName = new javax.swing.JLabel();
        BloodGroup = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        PersonName4 = new javax.swing.JLabel();
        Grade = new javax.swing.JLabel();
        PersonName8 = new javax.swing.JLabel();
        Working = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CurrentHeading2 = new javax.swing.JLabel();
        Heading1 = new javax.swing.JLabel();
        PersonName1 = new javax.swing.JLabel();
        Institution = new javax.swing.JLabel();
        PersonName2 = new javax.swing.JLabel();
        WorkPlace = new javax.swing.JLabel();
        PersonName5 = new javax.swing.JLabel();
        PersonName9 = new javax.swing.JLabel();
        WorkNumber = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        WorkAddress = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        PersonName3.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName3.setText("Phone Number");
        PersonName3.setAutoscrolls(true);

        PhoneNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PhoneNumber.setText("Empty");
        PhoneNumber.setAutoscrolls(true);

        PersonName7.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName7.setText("Date Of Birth");
        PersonName7.setAutoscrolls(true);

        DOB.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        DOB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DOB.setText("Empty");
        DOB.setAutoscrolls(true);

        jSeparator2.setAutoscrolls(true);
        jSeparator2.setFocusable(true);

        CurrentHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentHeading1.setText("Empty");

        Heading.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Personal Details");

        PersonName.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName.setText("Blood Group");
        PersonName.setAutoscrolls(true);

        BloodGroup.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        BloodGroup.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BloodGroup.setText("Empty");
        BloodGroup.setAutoscrolls(true);

        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PersonName4.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName4.setText("Grade / Year");
        PersonName4.setAutoscrolls(true);

        Grade.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Grade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Grade.setText("Empty");
        Grade.setAutoscrolls(true);

        PersonName8.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName8.setText("Working");
        PersonName8.setAutoscrolls(true);

        Working.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Working.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Working.setText("Empty");
        Working.setAutoscrolls(true);

        jSeparator3.setAutoscrolls(true);
        jSeparator3.setFocusable(true);

        CurrentHeading2.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CurrentHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentHeading2.setText("Empty");

        Heading1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        Heading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading1.setText("Current Details");

        PersonName1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName1.setText("Institution");
        PersonName1.setAutoscrolls(true);

        Institution.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        Institution.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Institution.setText("Empty");
        Institution.setAutoscrolls(true);

        PersonName2.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName2.setText("Work Place");
        PersonName2.setAutoscrolls(true);

        WorkPlace.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkPlace.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        WorkPlace.setText("Empty");
        WorkPlace.setAutoscrolls(true);

        PersonName5.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName5.setText("Work Address");
        PersonName5.setAutoscrolls(true);

        PersonName9.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        PersonName9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersonName9.setText("Work Number");
        PersonName9.setAutoscrolls(true);

        WorkNumber.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        WorkNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        WorkNumber.setText("Empty");
        WorkNumber.setAutoscrolls(true);

        WorkAddress.setEditable(false);
        WorkAddress.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jScrollPane2.setViewportView(WorkAddress);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentHeading2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PersonName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PersonName8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PersonName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Working, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Institution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Grade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PersonName2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PersonName5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonName9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WorkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentHeading2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PersonName4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PersonName8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Institution, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(Grade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Working)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(PersonName2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PersonName5)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonName9)
                    .addComponent(WorkNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadCurrentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadCurrentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodGroup;
    private javax.swing.JLabel CurrentHeading1;
    private javax.swing.JLabel CurrentHeading2;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel Grade;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel Institution;
    private javax.swing.JLabel PersonName;
    private javax.swing.JLabel PersonName1;
    private javax.swing.JLabel PersonName2;
    private javax.swing.JLabel PersonName3;
    private javax.swing.JLabel PersonName4;
    private javax.swing.JLabel PersonName5;
    private javax.swing.JLabel PersonName7;
    private javax.swing.JLabel PersonName8;
    private javax.swing.JLabel PersonName9;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JTextPane WorkAddress;
    private javax.swing.JLabel WorkNumber;
    private javax.swing.JLabel WorkPlace;
    private javax.swing.JLabel Working;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
